language: python

env:
  global:
    #- DEPENDS="cython>=0.19"
    - NO_NET=1

git:
  depth: 1000

matrix
  include:
    - python: 3.8
      dist: xenial
      sudo: true
      services:
        - xvfb
    - python: 3.9
      dist: xenial
      sudo: true
      services:
        - xvfb
        
allow_failures:
  - python: 3.9
  
install:
  - pip install numpy
  - pip install pandas
  - pip install matplotlib
  - pip install scipy
  - pip install codecov
  - pip install pytest-cov
  - pip install codacy-coverage

script:
  - py.test ./tests --cov=pyet --cov-report=xml

after_success:
   - python-codacy-coverage -r coverage.xml
